
grammar = rules:{rule} ;

rule = name:word '=' ! expre:expre ('.'|';') ! ;

expre = expre:option ;

option = opts:sequence {'|' ! opts:sequence } ;

sequence = elements:element { [','] elements:element } ;

element = named | term ;

named = [ name:word ] term:term ;

term = exp:(subexp | repeat | optional | special | atom) ; 

subexp = '(' ! exp:expre ')' ! ;

repeat = '{' !  expt:expre '}' ! plus:['-'|'+'] ! ;

optional = '[' ! exp:expre ']' ! ;

special = '?' ! exp:?/.*/? '?' ! ;

atom = exp:(token | word | pattern) ;

token = 
    (
    '"' exp:?/([^"]|\")*/?  '"' 
    | 
    "'" ?/([^']|\')*/?  "'" 
    ) 
    ;

word = exp:?/[-_A-Za-z0-9]/? ;

pattern = '?/' exp:?/.*/?   '/?' ;
